apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/toxics-space/git-ops.git
    targetRevision: HEAD
    path: ui
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated: {}
